// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzr083Z9ZLSekMbjDMacnlpUnSXxpzLGo',
    appId: '1:672257444728:web:d5daf197adb3d6653b568d',
    messagingSenderId: '672257444728',
    projectId: 'cabinetmedicalmobileappx',
    authDomain: 'cabinetmedicalmobileappx.firebaseapp.com',
    storageBucket: 'cabinetmedicalmobileappx.appspot.com',
    measurementId: 'G-0HP05K4BXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPoLuGPprFr-emFSmJP0vsqY55yM2iMyo',
    appId: '1:672257444728:android:e4224f8e15d9342c3b568d',
    messagingSenderId: '672257444728',
    projectId: 'cabinetmedicalmobileappx',
    storageBucket: 'cabinetmedicalmobileappx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh_pGSaXUvL2Fo_0TSA63LSE4sCIOJaHQ',
    appId: '1:672257444728:ios:1614b71e2e2c63a23b568d',
    messagingSenderId: '672257444728',
    projectId: 'cabinetmedicalmobileappx',
    storageBucket: 'cabinetmedicalmobileappx.appspot.com',
    iosBundleId: 'com.example.managementCabinetMedicalMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh_pGSaXUvL2Fo_0TSA63LSE4sCIOJaHQ',
    appId: '1:672257444728:ios:1614b71e2e2c63a23b568d',
    messagingSenderId: '672257444728',
    projectId: 'cabinetmedicalmobileappx',
    storageBucket: 'cabinetmedicalmobileappx.appspot.com',
    iosBundleId: 'com.example.managementCabinetMedicalMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzr083Z9ZLSekMbjDMacnlpUnSXxpzLGo',
    appId: '1:672257444728:web:bd86b6a2941f588b3b568d',
    messagingSenderId: '672257444728',
    projectId: 'cabinetmedicalmobileappx',
    authDomain: 'cabinetmedicalmobileappx.firebaseapp.com',
    storageBucket: 'cabinetmedicalmobileappx.appspot.com',
    measurementId: 'G-MX7DCTBN0N',
  );
}
